In [1]:
# importing pacakages
import pandas as pd
import numpy as np

# opening file from folder location via pandas
df = pd.read_csv(r'G:\Python projects\Job project\Movie - Data Set for Cleaning - Sheet1.csv')

# renaming columns for better clarity
df = df.rename(columns = {'movie_title': 'Movie Title', 'num_critic_for_reviews': 'Number of Critic Reviews', 'duration': 'Duration (mins)',
                         'DIRECTOR_facebook_likes': 'Facebook Likes (Director)', 'actor_3_facebook_likes': 'Facebook Likes (Actor 3)', 
                          'ACTOR_1_facebook_likes': 'Facebook Likes (Actor 1)', 'gross': 'Gross profit ($)', 'Cast_Total_facebook_likes': 
                         'Facebook Likes (Cast Total)', 'budget': 'Budget ($)', 'title_year': 'Year Released', 'num_user_for_reviews': 
                          'Number of User Reviews', 'ACTOR_2_facebook_likes': 'Facebook Likes (Actor 2)', 'imdb_score': 'IMDB Score (/10)', 
                         'num_voted_users': 'Number of Votes', 'facenumber_in_poster': 'Faces on Poster'})

# dropping unnecessary columns
df = df.drop(columns = ['title_year.1'])
df

# removing unnecessary strings
df['Movie Title'] = df['Movie Title'].str.replace('?','')
df['Movie Title'] = df['Movie Title'].str.replace('ÿ','')
df['Facebook Likes (Director)'] = df['Facebook Likes (Director)'].str.replace('"475"', '475')
                                                  
# reordering columns for calirty
# defining cols as variable and printing variable to assist with column reordering 
# cols = list(df.columns.values)
# print(cols)
df = df.reindex(columns=['Movie Title','Year Released', 'Duration (mins)', 'Budget ($)', 'Gross profit ($)', 'IMDB Score (/10)', 
                        'Number of Critic Reviews', 'Number of User Reviews', 'Number of Votes', 'Facebook Likes (Actor 1)', 
                        'Facebook Likes (Actor 2)', 'Facebook Likes (Actor 3)', 'Facebook Likes (Director)', 'Facebook Likes (Cast Total)', 'Faces on Poster'])

df

C:\Users\marwa\AppData\Local\Temp\ipykernel_19984\3071218053.py:21: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Movie Title'] = df['Movie Title'].str.replace('?','')

,Movie Title,Year Released,Duration (mins),Budget ($),Gross profit ($),IMDB Score (/10),Number of Critic Reviews,Number of User Reviews,Number of Votes,Facebook Likes (Actor 1),Facebook Likes (Actor 2),Facebook Likes (Actor 3),Facebook Likes (Director),Facebook Likes (Cast Total),Faces on Poster
0,Avatar,2009,178.0,237000000,760505847,7.9,723,3054,886204.0,1000,936.0,855,10,4834.0,NaN
1,Pirates of the Caribbean: At World's End,2007,NaN,300000000,309404152,7.1,302,1238,471220.0,40000,5000.0,1000,563,48350.0,NaN
2,Spectre,2015,148.0,245000000,200074175,6.8,602,994,275868.0,11000,393.0,161,20,11700.0,1.0
3,The Dark Knight Rises,2012,NaN,250000000,448130642,8.5,813,2701,1144337.0,27000,23000.0,23000,22000,106759.0,NaN
4,John Carter,2012,132.0,263700000,73058679,6.6,462,738,212204.0,640,632.0,530,475,1873.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,Harry Potter and the Half-Blood Prince,2009,153.0,250000000,301956980,7.5,375,973,321795.0,25000,11000.0,10000,282,58753.0,3.0
10,Batman v Superman: Dawn of Justice,2016,183.0,250000000,330249062,6.9,673,3018,NaN,15000,NaN,2000,NaN,24450.0,NaN
11,Superman Returns,2006,169.0,209000000,200069408,6.1,434,2367,240396.0,18000,10000.0,903,NaN,NaN,2.0
12,Quantum of Solace,2008,106.0,200000000,168368427,6.7,403,1243,330784.0,451,412.0,393,395,2023.0,1.0
13,Pirates of the Caribbean: Dead Man's Chest,2006,151.0,225000000,423032628,7.3,313,1832,522040.0,40000,5000.0,1000,563,48486.0,2.0

In [2]:
# saving clean dataset as csv to be accessed later
df.to_csv('Movie Dataset (clean).csv')